=== AuxoDAO/auxo-reporter/config/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "year": {
      "type": "integer"
    },
    "month": {
      "type": "integer"
    },
    "block_snapshot": {
      "type": "integer"
    },
    "distribution_window": {
      "type": "integer"
    },
    "rewards": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "string"
        },
        "address": {
          "type": "string",
          "minLength": 42,
          "maxLength": 42
        },
        "decimals": {
          "type": "integer"
        },
        "symbol": {
          "type": "string"
        }
      },
      "required": ["amount", "address", "decimals", "symbol"]
    },
    "arv_percentage": {
      "type": "integer"
    },
    "redistributions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "weight": {
            "type": "integer"
          },
          "address": {
            "type": "string",
            "minLength": 42,
            "maxLength": 42
          },
          "option": {
            "type": "string",
            "enum": ["transfer", "redistribute_prv"]
          }
        },
        "required": ["weight", "option"]
      }
    }
  },
  "required": ["year", "month", "block_snapshot", "distribution_window", "rewards", "arv_percentage", "redistributions"]
}

=== AuxoDAO/auxo-reporter/reporter/test/scenario_testing/inputs/scenario-1.json
{
  "year": 2099,
  "month": 2,
  "block_snapshot": 8743599,
  "distribution_window": 99,
  "rewards": {
    "amount": "500000000000000000000",
    "address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    "decimals": 18,
    "symbol": "WETH"
  },
  "arv_percentage": 60,
  "redistributions": [
    {
      "weight": 50,
      "address": "0x91d1608675646b73069CaD97c88Daeb42418754f",
      "option": "transfer"
    },
    {
      "weight": 50,
      "option": "redistribute_prv"
    }
  ]
}

=== AuxoDAO/auxo-reporter/config/6-23.json
{
  "$schema": "./schema.json",
  "year": 2023,
  "month": 6,
  "block_snapshot": 17720105,
  "distribution_window": 1,
  "rewards": {
    "amount": "25754357360000000000",
    "address": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
    "decimals": 18,
    "symbol": "WETH"
  },
  "arv_percentage": 70,
  "redistributions": [
    {
      "weight": 100,
      "option": "transfer",
      "address": "0x3bCF3Db69897125Aa61496Fc8a8B55A5e3f245d5"
    }
  ]
}
